### ISSUE TITLE
English version: STR instead of CTR?

### ISSUE THREAD

**Issue by marteaurouge** [ztiromoritz/pico-8-spick#8]
Saw that you're using STR instead of CTR? (it's in the german version as well, but not french),

Not sure this was a typo or maybe something I'm not aware of,

**Comment by ztiromoritz** [comment]
You mean the "Ctrl"-key in the shortcut section, right?
Hm, interesting Question.

First of all it has to be "STRG" instead of "STR". This appears on some german keyboard and means "Steuerung" and is the german translation of "Control" or "CTRL". But there are also German Keyboards with CTRL on it.
So using CTRL for both Englisch and German might be a good solution.
And it's even correct for French AZERTY-Keyboards, isn't it.

Remark: On Mac it is even another key, the command key or "CMD".

**Comment by ztiromoritz** [comment]
If there are now objections, I will close this issue.
